### PR TITLE
simplification thanks to upstream change

### PR DESCRIPTION
**Pull request by rmatthes**
upstream PR1633 has the terminal object in the functor category set to the functor that is constantly the terminal object - this is what was needed here

can only compile after merging PR1633 to UniMath

### CODE REVIEW

**Comment by rmatthes** [comment]
I now know how to avoid making irrelevant commits to trigger CI...

**Comment by rmatthes** [comment]
The failure of CI does not seem to have anything to do with my PR but rather with the CI setup. @m-lindgren : could you please have a look?

**Comment by m-lindgren** [comment]
Ah, this uses the old CI system. This must have been an issue since adding 'EnsureStructuredProofs' to UniMath.

Should I change the CI to a compositional build using Dune? Similar to how UniMath and SetHITs is setup today, this should make largecatmodules build in a matter of minutes. @benediktahrens your thoughts on this? 

The quick fix is to add `Tactics` to the current `make` command, but then it would take at least 2h until UniMath is compiled and we know if this PR compiles, and I think I can have a new CI system in place in a fraction of that time.

**Comment by rmatthes** [comment]
@m-lindgren With the satellite CI, the Dune configuration you provided is even more of a success story than for the main library. So, I would be very glad if you moved to compositional build.

**Comment by benediktahrens** [comment]
@m-lindgren : it would be fantastic if you could improve this repository's CI.

**Comment by m-lindgren** [comment]
Hopefully it works now.

**Comment by rmatthes** [comment]
The failure of CI build with dev was expected since there is ongoing upstream activity to resolve that problem.

**Comment by m-lindgren** [comment]
Doh, Yes of course, I was so confused why it failed. These circular dependencies between PR:s confuse me. :-)

We at least know that the ordinary build works with this PR.

**Comment by rmatthes** [comment]
And we'll have to wait for close to an hour to see if the main repo does now compile with the dev branch.

**Comment by m-lindgren** [comment]
Yeah, that's because githubs cache script doesn't allow us to save the cache if a job fails.

However I just found that there is an official cache-script currently in beta-testing that would allow us to save the cache even if the job failed. That might save us some time in the future.

**Comment by rmatthes** [comment]
It will save us time but also saves on computing resources, so this is of a concern for the entire planet. @m-lindgren: Thanks for your watchful eye on the newest developments.

**Comment by rmatthes** [comment]
Now, I do not understand why the build that is "required" is not started. I assume this needs a change in the CI configuration.

**Pull request merged**
